// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkQAsK_0lQPg9zDL-PPMueoeoAqc9Sp5w',
    appId: '1:881178665884:web:19a24b5a120c216ce59e59',
    messagingSenderId: '881178665884',
    projectId: 'rakwa-331713',
    authDomain: 'rakwa-331713.firebaseapp.com',
    databaseURL: 'https://rakwa-331713-default-rtdb.firebaseio.com',
    storageBucket: 'rakwa-331713.appspot.com',
    measurementId: 'G-P88KK464LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzDugd59L7iOpUmUdp3HoxnHNOmiI2rjE',
    appId: '1:881178665884:android:8025cfb4c1b4c6a9e59e59',
    messagingSenderId: '881178665884',
    projectId: 'rakwa-331713',
    databaseURL: 'https://rakwa-331713-default-rtdb.firebaseio.com',
    storageBucket: 'rakwa-331713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARcJwfHBkUl84WSlMIAGTL5dwJn-fmRnU',
    appId: '1:881178665884:ios:34de5ddc480fe556e59e59',
    messagingSenderId: '881178665884',
    projectId: 'rakwa-331713',
    databaseURL: 'https://rakwa-331713-default-rtdb.firebaseio.com',
    storageBucket: 'rakwa-331713.appspot.com',
    iosClientId: '881178665884-725a39h0fe8ilkaqsdqia8ujgi9sprog.apps.googleusercontent.com',
    iosBundleId: 'com.rakwa.rakwa',
  );
}
